version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: findmypet
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-dbless:
    image: kong/kong-gateway:3.5.0.3
    container_name: kong-dbless
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/kong/declarative/kong.yml'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002'
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    networks:
      - kong-net

volumes:
  postgres_data:

networks:
  kong-net:
    driver: bridge
